export const data = {
    totalPrice: 200000,
    vat: 0,
    discount: 5,
    paproductId: 190000,
    list: [
        {
            productId: 1,
            sku: 'SP0001',
            name: 'Đắc nhân tâm',
            featureImageUrl: 'https://inthienhang.com/wp-content/uploads/2020/03/mau-bia-sach-dep.jpg',
            quantity: 20,
            salePrice: 50000,
            discount: 5,
            totalPrice: 1000000,
        },
        {
            productId: 2,
            sku: 'SP0002',
            name: 'Đắc nhân tâm',
            featureImageUrl: 'https://inthienhang.com/wp-content/uploads/2020/03/mau-bia-sach-dep.jpg',
            quantity: 20,
            salePrice: 50000,
            discount: 5,
            totalPrice: 1000000,
        },
        {
            productId: 3,
            sku: 'SP0002',
            name: 'Đắc nhân tâm',
            featureImageUrl: 'https://inthienhang.com/wp-content/uploads/2020/03/mau-bia-sach-dep.jpg',
            quantity: 20,
            salePrice: 50000,
            discount: 5,
            totalPrice: 1000000,
        },
        {
            productId: 4,
            sku: 'SP0002',
            name: 'Đắc nhân tâm',
            featureImageUrl: 'https://inthienhang.com/wp-content/uploads/2020/03/mau-bia-sach-dep.jpg',
            quantity: 20,
            salePrice: 50000,
            discount: 5,
            totalPrice: 1000000,
        },
        {
            productId: 5,
            sku: 'SP0002',
            name: 'Đắc nhân tâm',
            featureImageUrl: 'https://inthienhang.com/wp-content/uploads/2020/03/mau-bia-sach-dep.jpg',
            quantity: 20,
            salePrice: 50000,
            discount: 5,
            totalPrice: 1000000,
        },
        {
            productId: 6,
            sku: 'SP0002',
            name: 'Đắc nhân tâm',
            featureImageUrl: 'https://inthienhang.com/wp-content/uploads/2020/03/mau-bia-sach-dep.jpg',
            quantity: 20,
            salePrice: 50000,
            discount: 5,
            totalPrice: 1000000,
        },

        {
            productId: 7,
            sku: 'SP0002',
            name: 'Đắc nhân tâm',
            featureImageUrl: 'https://inthienhang.com/wp-content/uploads/2020/03/mau-bia-sach-dep.jpg',
            quantity: 20,
            salePrice: 50000,
            discount: 5,
            totalPrice: 1000000,
        },
        {
            productId: 8,
            sku: 'SP0002',
            name: 'Đắc nhân tâm',
            featureImageUrl: 'https://inthienhang.com/wp-content/uploads/2020/03/mau-bia-sach-dep.jpg',
            quantity: 20,
            salePrice: 50000,
            discount: 5,
            totalPrice: 1000000,
        },
    ],
};
